In [2]:
import requests
import time
import json

import pandas as pd

In [2]:
pagina = 1 
uasgs = []
while True:
    data = requests.get(f'https://dadosabertos.compras.gov.br/modulo-uasg/1_consultarUasg?pagina={pagina}&statusUasg=true').json()
    
    uasgs += data['resultado']
    
    if data['paginasRestantes'] == 0:
        break
    time.sleep(1)
    pagina += 1

In [ ]:
uasgs_df = pd.DataFrame(uasgs)

uasgs_df.drop(columns=[
    'usoSisg', 'adesaoSiasg', 'codigoUnidadePolo', 'nomeUnidadePolo', 'codigoUnidadeEspelho', 'nomeUnidadeEspelho', 'uasgCadastradora', 'cnpjCpfUasg', 'codigoOrgao', 'cnpjCpfOrgao', 'cnpjCpfOrgaoVinculado', 'cnpjCpfOrgaoSuperior', 'codigoSiorg', 'statusUasg', 'dataImplantacaoSidec', 'dataHoraMovimento'
], inplace=True)

uasgs_df

,codigoUasg,nomeUasg,siglaUf,codigoMunicipio,codigoMunicipioIbge,nomeMunicipioIbge
0,996612,CONSELHO REGIONAL DE CONTABILIDADE - PA,PA,4278.0,1501402.0,BELÉM
1,990224,ESP-AG. DE BIBL. E COLEÇÕES DIGITAIS - USP,SP,71072.0,3550308.0,SÃO PAULO
2,990223,ESP-CENTRAL DE COMPRAS - TECNOLÓGICAS,SP,62910.0,3509502.0,CAMPINAS
3,990222,ESP-CENTRAL DE COMPRAS - HUMANIDADES E ARTES,SP,62910.0,3509502.0,CAMPINAS
4,990221,ESP-CENTRAL DE COMPRAS - EXATAS,SP,62910.0,3509502.0,CAMPINAS
...,...,...,...,...,...,...
21493,020001,SENADO FEDERAL,DF,97012.0,5300108.0,BRASÍLIA
21494,015873,INST FED.DE EDUC. CIENC.E.TEC.DA PARAIBA,PB,21296.0,2511400.0,PICUÍ
21495,010090,FUNDO ROTATIVO DA CAMARA DOS DEPUTADOS,DF,97012.0,5300108.0,BRASÍLIA
21496,010002,CAMARA DOS DEPUTADOS - UG P/CONSULTA,DF,97012.0,5300108.0,BRASÍLIA
21497,010001,CAMARA DOS DEPUTADOS,DF,97012.0,5300108.0,BRASÍLIA

In [20]:
with open('uasgs.json', 'w+', encoding='latin-1') as file:
    uasgs_df.to_json(file, indent=4, orient='records', force_ascii=False)
    # json.dump(uasgs_df, file, indent=4, ensure_ascii=False)

In [5]:
pd.read_json('uasgs.json', encoding='latin-1')

,codigoUasg,nomeUasg,siglaUf,codigoMunicipio,codigoMunicipioIbge,nomeMunicipioIbge
0,996612,CONSELHO REGIONAL DE CONTABILIDADE - PA,PA,4278.0,1501402.0,BELÉM
1,990224,ESP-AG. DE BIBL. E COLEÇÕES DIGITAIS - USP,SP,71072.0,3550308.0,SÃO PAULO
2,990223,ESP-CENTRAL DE COMPRAS - TECNOLÓGICAS,SP,62910.0,3509502.0,CAMPINAS
3,990222,ESP-CENTRAL DE COMPRAS - HUMANIDADES E ARTES,SP,62910.0,3509502.0,CAMPINAS
4,990221,ESP-CENTRAL DE COMPRAS - EXATAS,SP,62910.0,3509502.0,CAMPINAS
...,...,...,...,...,...,...
21493,20001,SENADO FEDERAL,DF,97012.0,5300108.0,BRASÍLIA
21494,15873,INST FED.DE EDUC. CIENC.E.TEC.DA PARAIBA,PB,21296.0,2511400.0,PICUÍ
21495,10090,FUNDO ROTATIVO DA CAMARA DOS DEPUTADOS,DF,97012.0,5300108.0,BRASÍLIA
21496,10002,CAMARA DOS DEPUTADOS - UG P/CONSULTA,DF,97012.0,5300108.0,BRASÍLIA
21497,10001,CAMARA DOS DEPUTADOS,DF,97012.0,5300108.0,BRASÍLIA